-- AlterTable
ALTER TABLE "book" ALTER COLUMN "title" SET DATA TYPE VARCHAR(8000),
ALTER COLUMN "synopsis" SET DATA TYPE VARCHAR(8000),
ALTER COLUMN "authors" SET DATA TYPE VARCHAR(8000),
ALTER COLUMN "google_image_url" SET DATA TYPE VARCHAR(8000);
